services:

  db:
    container_name: ${PETS_CONTAINER_NAME}
    image: ${PETS_IMAGE_NAME}
    hostname: ${PETS_POSTGRES_DB_HOST}
    ports:
      - ${PETS_POSTGRES_DB_PORT}:5432
    environment:
      - POSTGRES_USER=${PETS_POSTGRES_DB_USER}
      - POSTGRES_PASSWORD=${PETS_POSTGRES_DB_PASS}
      - POSTGRES_DB=${PETS_POSTGRES_DB_NAME}
      - TZ=${PETS_TIMEZONE}
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5
      start_period: 10s
      timeout: 5s