from typing import List, Optional, TYPE_CHECKING
from pydantic import BaseModel, ConfigDict
from datetime import datetime

if TYPE_CHECKING:
    from app.schemas.pet_schemas import PetReadNR


class TrainerBase(BaseModel):
    ''' Owners Base Schema '''
    name: str
    description: str
    phone_no: str
    email: str
    date_started: datetime

    # Allow for Object Relational Mapping (Treating relation like nested objects)
    model_config = ConfigDict(from_attributes=True)


class TrainerCreate(TrainerBase):
    ''' Trainer Create Schema, not autogenerated thus needs to input is on creation '''
    trainer_id: str


class TrainerReadNR(TrainerBase):
    ''' Trainer Read w/o relation Schema '''
    trainer_id: str


class TrainerReadWR(TrainerReadNR):
    ''' Trainer Read w/ relation Schema '''

    pets: List["PetReadNR"]


class TrainerUpdate(TrainerBase):
    ''' Trainer update schema '''
    trainer_id: Optional[str] = None  # Trainer ID in this case is updatable, Pet and Owner cannot update their ID
    name: Optional[str] = None
    description: Optional[str] = None
    phone_no: Optional[str] = None
    email: Optional[str] = None

from app.schemas.pet_schemas import PetReadNR
TrainerReadWR.model_rebuild()
