from typing import List, Optional
from pydantic import BaseModel
from datetime import datetime

'''
======== BASE SCHEMAS ========
Schema containing information that will be expected to all other schema
'''

class TrainerBase(BaseModel):
    ''' Owners Base Schema '''
    name: str
    description: str
    phone_no: str
    email: str
    date_started: datetime

    # Allow for Object Relational Mapping (Treating relation like nested objects)
    class Config:
        orm_mode = True

'''
======== CREATE SCHEMA ========
Schema inherit Base schemas, for when new instance of object is created
 - Used when unknowable data is required
 - Sometimes used to prevent sensitive data from leaking into the other API.
'''

class TrainerCreate(TrainerBase):
    ''' Trainer Create Schema, not autogenerated thus needs to input is on creation '''
    trainer_id: str

'''
======== READ NO RELATION ========
Schema inherit Base schemas, for reading object data WITHOUT relational information
 - Used in "Get All" cruds to provide reduced network load on large complex data
 - Used when relationships are represented in the return.
       - Pets is dependent on the 3 other models, returning all that data for every pet is heavy on the network.
 - Used when data are self-referential, self referential data could result in a recursive loop as it expands repeatedly
'''

class TrainerReadNR(TrainerBase):
    ''' Trainer Read w/o relation Schema '''
    trainer_id: str

'''
======== READ WITH RELATION ========
Schema inherit No Relation schemas, for reading object data WITH relational information
 - Used when data is specfied and requires pulling all data of its relation
 - Built off the non-relational read schema
 - Pulled data uses non-relational read to prevent heavy network load
'''

class TrainerReadWR(TrainerReadNR):
    ''' Trainer Read w/ relation Schema '''
    from app.schemas.pet_schemas import PetReadNR
    pets: List[PetReadNR]

'''
======== UPDATE SCHEMA ========
Schema inherit Base schema, for updating existing information
On update, any optional field not included will not be updated
Typically a carbon copy of the base field with everything overwritten with the Optional typing
The "= None" is a default you initialise which allows for you to not require inputting the field in the body of the request
'''

class TrainerUpdate(TrainerBase):
    ''' Trainer update schema '''
    trainer_id: Optional[str] = None # Trainer ID in this case is updatable, Pet and Owner cannot update their ID
    name: Optional[str] = None
    description: Optional[str] = None
    phone_no: Optional[str] = None
    email: Optional[str] = None

