'''Trainer Schemas

Contains the pydantic structures used to enforce the typing and return values during operation

Schema Types:
- Base Schema: Acts as the starting base containing all the fields that are shared with all remaining schema
- Create Schema: Inherited from Base, contains any new information that is unique to the input during creation
- ReadNR Schema: Inherited from Base, contains all the information that is to be read. Does not include any relation data from other linked tables
- ReadWR Schema: Inherited from ReadNR, includes relation data from other linked table
- Update Schema: Inherited from Base, includes all the fields that can be updated, "None" defaults means you do strictly have to include those fields in the body.

Notes:
- TYPE_CHECKING check for the imports are to allow for IDE checking
- Imports of the shared models and the model rebuild is to avoid circular import
'''

from app.schemas.pet_schemas import PetReadNR
from typing import List, Optional, TYPE_CHECKING
from pydantic import BaseModel, ConfigDict
from datetime import datetime

if TYPE_CHECKING:
    from app.schemas.pet_schemas import PetReadNR


class TrainerBase(BaseModel):
    ''' Owners Base Schema '''
    name: str
    description: str
    phone_no: str
    email: str
    date_started: datetime

    # Allow for Object Relational Mapping (Treating relation like nested objects)
    model_config = ConfigDict(from_attributes=True)


class TrainerCreate(TrainerBase):
    ''' Trainer Create Schema, not autogenerated thus needs to input is on creation '''
    trainer_id: str


class TrainerReadNR(TrainerBase):
    ''' Trainer Read w/o relation Schema '''
    trainer_id: str


class TrainerReadWR(TrainerReadNR):
    ''' Trainer Read w/ relation Schema '''
    pets: List["PetReadNR"]


class TrainerUpdate(TrainerBase):
    ''' Trainer update schema '''
    trainer_id: Optional[str] = None  # Trainer ID in this case is updatable, Pet and Owner cannot update their ID
    name: Optional[str] = None
    description: Optional[str] = None
    phone_no: Optional[str] = None
    email: Optional[str] = None


TrainerReadWR.model_rebuild()
